DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"ShoeCatalogs" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_ShoeCatalogs" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Size" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "SizeName" NVARCHAR2(2000),
    CONSTRAINT "PK_Size" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Users" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(2000),
    "Email" NVARCHAR2(2000),
    "DateOfBirth" TIMESTAMP(7) NOT NULL,
    "IsAdmin" NUMBER(1) NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Shoes" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Title" NVARCHAR2(2000),
    "Price" BINARY_DOUBLE NOT NULL,
    "Description" NVARCHAR2(2000),
    "Trademark" NVARCHAR2(2000),
    "Quantity" NUMBER(10) NOT NULL,
    "ShoeCatalogId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_Shoes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shoes_ShoeCatalogs_ShoeCatalogId" FOREIGN KEY ("ShoeCatalogId") REFERENCES "ShoeCatalogs" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Orders" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "TotalPrice" BINARY_DOUBLE NOT NULL,
    "DateCreated" TIMESTAMP(7) NOT NULL,
    "Email" NVARCHAR2(2000),
    "Address" NVARCHAR2(2000),
    "PhoneNumber" NVARCHAR2(2000),
    "State" NVARCHAR2(2000),
    "IsPaid" NUMBER(1) NOT NULL,
    "IsCanceled" NUMBER(1) NOT NULL,
    "UserId" NUMBER(10),
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Evolutions" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "NumberOfStar" NUMBER(10) NOT NULL,
    "Content" NVARCHAR2(2000),
    "UserId" NUMBER(10) NOT NULL,
    "ShoeId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_Evolutions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evolutions_Shoes_ShoeId" FOREIGN KEY ("ShoeId") REFERENCES "Shoes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Evolutions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Image" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "ImageSource" NCLOB,
    "ShoeId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_Image" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Image_Shoes_ShoeId" FOREIGN KEY ("ShoeId") REFERENCES "Shoes" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"ShoeSizes" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "ShoeId" NUMBER(10) NOT NULL,
    "SizeId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_ShoeSizes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShoeSizes_Shoes_ShoeId" FOREIGN KEY ("ShoeId") REFERENCES "Shoes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ShoeSizes_Size_SizeId" FOREIGN KEY ("SizeId") REFERENCES "Size" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"OrderDetails" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "IntoMoney" BINARY_DOUBLE NOT NULL,
    "Size" NVARCHAR2(2000),
    "Quantity" NUMBER(10) NOT NULL,
    "ShoeId" NUMBER(10) NOT NULL,
    "OrderId" NUMBER(10),
    "UserId" NUMBER(10),
    CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id"),
    CONSTRAINT "FK_OrderDetails_Shoes_ShoeId" FOREIGN KEY ("ShoeId") REFERENCES "Shoes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderDetails_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"OrderProgress" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Content" NVARCHAR2(2000),
    "DateCreated" TIMESTAMP(7) NOT NULL,
    "OrderId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_OrderProgress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderProgress_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
)';
END;
/

CREATE INDEX "IX_Evolutions_ShoeId" ON "Evolutions" ("ShoeId")
/

CREATE INDEX "IX_Evolutions_UserId" ON "Evolutions" ("UserId")
/

CREATE INDEX "IX_Image_ShoeId" ON "Image" ("ShoeId")
/

CREATE INDEX "IX_OrderDetails_OrderId" ON "OrderDetails" ("OrderId")
/

CREATE INDEX "IX_OrderDetails_ShoeId" ON "OrderDetails" ("ShoeId")
/

CREATE INDEX "IX_OrderDetails_UserId" ON "OrderDetails" ("UserId")
/

CREATE INDEX "IX_OrderProgress_OrderId" ON "OrderProgress" ("OrderId")
/

CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId")
/

CREATE INDEX "IX_Shoes_ShoeCatalogId" ON "Shoes" ("ShoeCatalogId")
/

CREATE INDEX "IX_ShoeSizes_ShoeId" ON "ShoeSizes" ("ShoeId")
/

CREATE INDEX "IX_ShoeSizes_SizeId" ON "ShoeSizes" ("SizeId")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220106053124_InitDb', N'5.0.13')
/

ALTER TABLE "OrderDetails" DROP CONSTRAINT "FK_OrderDetails_Orders_OrderId"
/

ALTER TABLE "OrderDetails" ADD CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220106072513_UpdateDb', N'5.0.13')
/

